#!/bin/sh
# Materialize rite.toml from environment at container start.
# A fully-formed config mounted at /etc/rite/rite.mounted.toml wins.
set -eu

CONF="${RITE_CONFIG:-/etc/rite/rite.toml}"
mkdir -p "$(dirname "$CONF")"

if [ -f /etc/rite/rite.mounted.toml ]; then
  echo "Using mounted rite config." >&2
  cp /etc/rite/rite.mounted.toml "$CONF"
  exec "$@"
fi

IRIS_URL="${RITE_IRIS_BASE_URL:-}"

{
  echo "# Generated by docker-entrypoint.sh — do not edit in place."
  if [ -n "$IRIS_URL" ]; then
    echo ""
    echo "[sources.iris]"
    echo "enabled = true"
    echo "base_url = \"$IRIS_URL\""
  fi
} > "$CONF"

exec "$@"
